cities = [
  { region_code: "SA-01", name_en: "Riyadh", name_ar: "الرياض" },
  { region_code: "SA-01", name_en: "Dir'iyyah", name_ar: "الدرعية" },
  { region_code: "SA-01", name_en: "Al-Kharj", name_ar: "الخرج" },
  { region_code: "SA-01", name_en: "Al-Duwadmi", name_ar: "الدوادمي" },
  { region_code: "SA-01", name_en: "Al-Majmaah", name_ar: "المجمعة" },
  { region_code: "SA-01", name_en: "Al-Gway'iyyah", name_ar: "القويعية" },
  { region_code: "SA-01", name_en: "Al-Aflaj", name_ar: "الأفلاج" },
  { region_code: "SA-01", name_en: "Wadi Ad-Dawasir", name_ar: "وادي الدواسر" },
  { region_code: "SA-01", name_en: "Al-Zulfi", name_ar: "الزلفي" },
  { region_code: "SA-01", name_en: "Shagra", name_ar: "شقراء" },
  { region_code: "SA-01", name_en: "Hotat Bani Tamim", name_ar: "حوطة بني تميم" },
  { region_code: "SA-01", name_en: "Afif", name_ar: "عفيف" },
  { region_code: "SA-01", name_en: "Al-Ghat", name_ar: "الغاط" },
  { region_code: "SA-01", name_en: "Al-Sulayyil", name_ar: "السليل" },
  { region_code: "SA-01", name_en: "Dhruma", name_ar: "ضرماء" },
  { region_code: "SA-01", name_en: "Al-Muzahmiyyah", name_ar: "المزاحمية" },
  { region_code: "SA-01", name_en: "Rimah", name_ar: "رماح" },
  { region_code: "SA-01", name_en: "Thadig", name_ar: "ثادق" },
  { region_code: "SA-01", name_en: "Huraymila", name_ar: "حريملاء" },
  { region_code: "SA-01", name_en: "Al-Hareeg", name_ar: "الحريق" },
  { region_code: "SA-01", name_en: "Marat", name_ar: "مرات" },
  { region_code: "SA-01", name_en: "Ad-Dilam", name_ar: "الدلم" },
  { region_code: "SA-01", name_en: "Harmah", name_ar: "حرمة" },
  { region_code: "SA-01", name_en: "LAYLA", name_ar: "ليلى" },
  { region_code: "SA-01", name_en: "TUMAIR", name_ar: "تمير" },
  { region_code: "SA-01", name_en: "Al-Artawiyah", name_ar: "الأرطاوية" },
  { region_code: "SA-01", name_en: "Al-Bijadiyah", name_ar: "البجادية" },
  { region_code: "SA-01", name_en: "Al-Badi Al-Shamali", name_ar: "البديع الشمالي" },
  { region_code: "SA-01", name_en: "Al-Jubaylah", name_ar: "الجبيلة" },
  { region_code: "SA-01", name_en: "Al-Hair", name_ar: "الحاير" },
  { region_code: "SA-01", name_en: "Al-Ruwaydah", name_ar: "الرويضة" },
  { region_code: "SA-01", name_en: "As-Saih", name_ar: "السيح" },
  { region_code: "SA-01", name_en: "Ash-Shadidah", name_ar: "الشديدة" },
  { region_code: "SA-01", name_en: "Al-Amajiyah", name_ar: "العماجية" },
  { region_code: "SA-01", name_en: "Al-Uyaynah", name_ar: "العيينة" },
  { region_code: "SA-01", name_en: "King Abdulaziz Military Academy", name_ar: "الكلية الحربية" },
  { region_code: "SA-01", name_en: "An-Nayfiyah", name_ar: "النايفية" },
  { region_code: "SA-01", name_en: "Al-Hayathim", name_ar: "الهياثم" },
  { region_code: "SA-01", name_en: "Banban", name_ar: "بنبان" },
  { region_code: "SA-01", name_en: "Hawtat Sudayr", name_ar: "حوطة سدير" },
  { region_code: "SA-01", name_en: "Rawdat Sudayr", name_ar: "روضة سدير" },
  { region_code: "SA-01", name_en: "Sajir", name_ar: "ساجر" },
  { region_code: "SA-01", name_en: "Irqah", name_ar: "عرقة" },
  { region_code: "SA-01", name_en: "Prince Sultan Air Base", name_ar: "قاعدة الأمير سلطان" },
  { region_code: "SA-01", name_en: "Mulham", name_ar: "ملهم" },
  { region_code: "SA-02", name_en: "Makkah", name_ar: "مكة المكرمة" },
  { region_code: "SA-02", name_en: "Jeddah", name_ar: "جدة" },
  { region_code: "SA-02", name_en: "Al-Taif", name_ar: "الطائف" },
  { region_code: "SA-02", name_en: "Al-Qunfudhah", name_ar: "القنفذة" },
  { region_code: "SA-02", name_en: "Al-Lith", name_ar: "الليث" },
  { region_code: "SA-02", name_en: "Rabigh", name_ar: "رابغ" },
  { region_code: "SA-02", name_en: "Khulays", name_ar: "خليص" },
  { region_code: "SA-02", name_en: "Al-Khurmah", name_ar: "الخرمة" },
  { region_code: "SA-02", name_en: "Ranyah", name_ar: "رنية" },
  { region_code: "SA-02", name_en: "Turubah", name_ar: "تربة" },
  { region_code: "SA-02", name_en: "Al-Jumum", name_ar: "الجموم" },
  { region_code: "SA-02", name_en: "Al-Kamil", name_ar: "الكامل" },
  { region_code: "SA-02", name_en: "Al-Mowaih", name_ar: "المويه" },
  { region_code: "SA-02", name_en: "Misan", name_ar: "ميسان" },
  { region_code: "SA-02", name_en: "Adum", name_ar: "أضم" },
  { region_code: "SA-02", name_en: "Bahra", name_ar: "بحرة" },
  { region_code: "SA-02", name_en: "Al-Henakiyah", name_ar: "الحناكية" },
  { region_code: "SA-02", name_en: "KING ABDULLAH ECONOMIC CITY", name_ar: "مدينة الملك عبدالله الاقتصادية" },
  { region_code: "SA-02", name_en: "Al-Hawiyah", name_ar: "الحوية" },
  { region_code: "SA-02", name_en: "Al-Rumaydah", name_ar: "الرميدة" },
  { region_code: "SA-02", name_en: "As-Sail", name_ar: "السيل" },
  { region_code: "SA-02", name_en: "As-Sail As-Saghir", name_ar: "السيل الصغير" },
  { region_code: "SA-02", name_en: "Ash-Shuaybah", name_ar: "الشعيبة" },
  { region_code: "SA-02", name_en: "As-Saffah", name_ar: "الصفة" },
  { region_code: "SA-02", name_en: "Al-Arfa", name_ar: "العرفاء" },
  { region_code: "SA-02", name_en: "Al-Qawz", name_ar: "القوز" },
  { region_code: "SA-02", name_en: "Al-Muzaylif", name_ar: "المظيلف" },
  { region_code: "SA-02", name_en: "Al-Hada", name_ar: "الهدا" },
  { region_code: "SA-02", name_en: "Umm Al-Awqab", name_ar: "أم الأوقب" },
  { region_code: "SA-02", name_en: "Umm Al-Dawm", name_ar: "أم الدوم" },
  { region_code: "SA-02", name_en: "Thuwal", name_ar: "ثول" },
  { region_code: "SA-02", name_en: "Dhahban", name_ar: "ذهبان" },
  { region_code: "SA-02", name_en: "Shaab Makkah", name_ar: "شعب مكا" },
  { region_code: "SA-02", name_en: "Ashirah", name_ar: "عشيرة" },
  { region_code: "SA-02", name_en: "Ghuran", name_ar: "غران" },
  { region_code: "SA-02", name_en: "Qiya", name_ar: "قياء" },
  { region_code: "SA-02", name_en: "Mastorah", name_ar: "مستورة" },
  { region_code: "SA-02", name_en: "Malkan", name_ar: "ملكان" },
  { region_code: "SA-02", name_en: "Nimrah", name_ar: "نمرة" },
  { region_code: "SA-02", name_en: "Al-Muwaih Al-Gadeem", name_ar: "المويه القديم" },
  { region_code: "SA-03", name_en: "Al-Madinah Al-Munawwarah", name_ar: "المدينة المنورة" },
  { region_code: "SA-03", name_en: "Yanbu", name_ar: "ينبع" },
  { region_code: "SA-03", name_en: "Al-Ula", name_ar: "العلا" },
  { region_code: "SA-03", name_en: "Mahd adh Dhahab", name_ar: "مهد الذهب" },
  { region_code: "SA-03", name_en: "Badr", name_ar: "بدر" },
  { region_code: "SA-03", name_en: "Khaybar", name_ar: "خيبر" },
  { region_code: "SA-03", name_en: "Al-Aqul", name_ar: "العاقول" },
  { region_code: "SA-03", name_en: "Al-Ais", name_ar: "العيص" },
  { region_code: "SA-03", name_en: "Al-Thamad", name_ar: "الثمد" },
  { region_code: "SA-03", name_en: "Yanbu Industrial City", name_ar: "ينبع الصناعية" },
  { region_code: "SA-04", name_en: "Al-Dammam", name_ar: "الدمام" },
  { region_code: "SA-04", name_en: "Al-Ahsa", name_ar: "الأحساء" },
  { region_code: "SA-04", name_en: "Hafar Al-Batin", name_ar: "حفر الباطن" },
  { region_code: "SA-04", name_en: "Al-Jubail", name_ar: "الجبيل" },
  { region_code: "SA-04", name_en: "Al-Qatif", name_ar: "القطيف" },
  { region_code: "SA-04", name_en: "Al-Khobar", name_ar: "الخبر" },
  { region_code: "SA-04", name_en: "Al-Khafji", name_ar: "الخفجي" },
  { region_code: "SA-04", name_en: "Ras Tanurah", name_ar: "رأس تنورة" },
  { region_code: "SA-04", name_en: "Buqayq", name_ar: "بقيق" },
  { region_code: "SA-04", name_en: "Al-Nairyah", name_ar: "النعيرية" },
  { region_code: "SA-04", name_en: "Qaryat Al-Ulya", name_ar: "قرية العليا" },
  { region_code: "SA-04", name_en: "Alodaid", name_ar: "العديد" },
  { region_code: "SA-04", name_en: "Dhahran", name_ar: "الظهران" },
  { region_code: "SA-04", name_en: "Al-HUFUF", name_ar: "الهفوف" },
  { region_code: "SA-04", name_en: "Al-MUBARRAZ", name_ar: "المبرز" },
  { region_code: "SA-04", name_en: "Al-Tuwaythir", name_ar: "التويثير" },
  { region_code: "SA-04", name_en: "Al-Thuqbah", name_ar: "الثقبة" },
  { region_code: "SA-04", name_en: "Al-Jarudiyah", name_ar: "الجارودية" },
  { region_code: "SA-04", name_en: "Jubail Industrial City", name_ar: "الجبيل الصناعية" },
  { region_code: "SA-04", name_en: "Al-Awjam", name_ar: "الأوجام" },
  { region_code: "SA-04", name_en: "Al-Jarn", name_ar: "الجرن" },
  { region_code: "SA-04", name_en: "Al-Jish", name_ar: "الجش" },
  { region_code: "SA-04", name_en: "Al-Jishah", name_ar: "الجشة" },
  { region_code: "SA-04", name_en: "Al-Jafr", name_ar: "الجفر" },
  { region_code: "SA-04", name_en: "Al-Hulaylah", name_ar: "الحليلة" },
  { region_code: "SA-04", name_en: "Al-Hawtah", name_ar: "الحوطة" },
  { region_code: "SA-04", name_en: "Al-Khuwaylidiyah", name_ar: "الخويلدية" },
  { region_code: "SA-04", name_en: "Al-Dhibiyah", name_ar: "الذيبية" },
  { region_code: "SA-04", name_en: "Ar-Rumaylah", name_ar: "الرميلة" },
  { region_code: "SA-04", name_en: "Ash-Shuqaiq", name_ar: "الشقيق" },
  { region_code: "SA-04", name_en: "Ash-Shaharin", name_ar: "الشهارين" },
  { region_code: "SA-04", name_en: "At-Taraf", name_ar: "الطرف" },
  { region_code: "SA-04", name_en: "Al-Umran", name_ar: "العمران" },
  { region_code: "SA-04", name_en: "Al-Awamiyah", name_ar: "العوامية" },
  { region_code: "SA-04", name_en: "Al-Uyun", name_ar: "العيون" },
  { region_code: "SA-04", name_en: "Al-Ghuwaybah", name_ar: "الغويبة" },
  { region_code: "SA-04", name_en: "Al-Fudul", name_ar: "الفضول" },
  { region_code: "SA-04", name_en: "Al-Qarah", name_ar: "القارة" },
  { region_code: "SA-04", name_en: "Al-Qudayh", name_ar: "القديح" },
  { region_code: "SA-04", name_en: "Al-Qurayn", name_ar: "القرين" },
  { region_code: "SA-04", name_en: "Al-Qaysumah", name_ar: "القيصومة" },
  { region_code: "SA-04", name_en: "Al-Kilabiyah", name_ar: "الكلابية" },
  { region_code: "SA-04", name_en: "DARIN", name_ar: "دارين" },
  { region_code: "SA-04", name_en: "'INAK", name_ar: "عنك" },
  { region_code: "SA-04", name_en: "SAFWA", name_ar: "صفوى" },
  { region_code: "SA-04", name_en: "SAYHAT", name_ar: "سيهات" },
  { region_code: "SA-04", name_en: "TAROUT", name_ar: "تاروت" },
  { region_code: "SA-04", name_en: "Al-Malahah", name_ar: "الملاحة" },
  { region_code: "SA-04", name_en: "Al-Mansurah", name_ar: "المنصورة" },
  { region_code: "SA-04", name_en: "Al-Munayzilah", name_ar: "المنيزلة" },
  { region_code: "SA-04", name_en: "An-Nabiyah", name_ar: "النابية" },
  { region_code: "SA-04", name_en: "Al-Battaliyah", name_ar: "البطالية" },
  { region_code: "SA-04", name_en: "Al-Tubi", name_ar: "التوبي" },
  { region_code: "SA-04", name_en: "Al-Markaz", name_ar: "المركز" },
  { region_code: "SA-04", name_en: "Umm Al-Hamam", name_ar: "أم الحمام" },
  { region_code: "SA-04", name_en: "Umm Al-Sahik", name_ar: "أم الساهك" },
  { region_code: "SA-04", name_en: "Iskan Al-Kilabiyah", name_ar: "إسكان الكلابية" },
  { region_code: "SA-04", name_en: "Haradh", name_ar: "حرض" },
  { region_code: "SA-04", name_en: "Hillat Muhaysh", name_ar: "حلة محيش" },
  { region_code: "SA-04", name_en: "King Khalid Military City", name_ar: "مدينة الملك خالد العسكرية" },
  { region_code: "SA-04", name_en: "Muraykh", name_ar: "مريخ" },
  { region_code: "SA-04", name_en: "Desalination Plant", name_ar: "محطة التحلية" },
  { region_code: "SA-14", name_en: "Abha", name_ar: "أبها" },
  { region_code: "SA-14", name_en: "Khamis Mushait", name_ar: "خميس مشيط" },
  { region_code: "SA-14", name_en: "Bisha", name_ar: "بيشة" },
  { region_code: "SA-14", name_en: "Al-Namas", name_ar: "النماص" },
  { region_code: "SA-14", name_en: "Muhayil Aseer", name_ar: "محايل عسير" },
  { region_code: "SA-14", name_en: "Tathlith", name_ar: "تثليث" },
  { region_code: "SA-14", name_en: "Sarat Abidah", name_ar: "سراة عبيدة" },
  { region_code: "SA-14", name_en: "RojAl-Alma", name_ar: "رجال ألمع" },
  { region_code: "SA-14", name_en: "Al-Janfur", name_ar: "الجنفور" },
  { region_code: "SA-14", name_en: "Al-Alayah", name_ar: "العلاية" },
  { region_code: "SA-14", name_en: "Al-Majardah", name_ar: "المجاردة" },
  { region_code: "SA-14", name_en: "Al-Wadiyayn", name_ar: "الواديين" },
  { region_code: "SA-14", name_en: "Dhahran Al-Janub", name_ar: "ظهران الجنوب" },
  { region_code: "SA-14", name_en: "Farat Turayb", name_ar: "فرعة طريب" },
  { region_code: "SA-14", name_en: "Al Rayhan", name_ar: "آل ريحان" },
  { region_code: "SA-14", name_en: "Bahr Abu Sukaynah", name_ar: "بحر أبو سكينة" },
  { region_code: "SA-14", name_en: "Sinaabirah", name_ar: "سنعبرة" },
  { region_code: "SA-14", name_en: "Belgarn", name_ar: "بلقرن" },
  { region_code: "SA-14", name_en: "Al-Ithnain", name_ar: "الاثنين" },
  { region_code: "SA-14", name_en: "Ahad Rafidah", name_ar: "أحد رفيدة" },
  { region_code: "SA-14", name_en: "Al-Majaridah", name_ar: "المجاردية" },
  { region_code: "SA-14", name_en: "Al-Birk", name_ar: "البرك" },
  { region_code: "SA-14", name_en: "Bareq", name_ar: "بارق" },
  { region_code: "SA-14", name_en: "Tanomah", name_ar: "تنومة" },
  { region_code: "SA-14", name_en: "Tereeb", name_ar: "طريب" },
  { region_code: "SA-14", name_en: "BILLASMAR", name_ar: "بللسمر" },
  { region_code: "SA-14", name_en: "SABT Al-'ALAYAH", name_ar: "سبت العلاية" },
  { region_code: "SA-14", name_en: "TENDAHA", name_ar: "تندحة" },
  { region_code: "SA-07", name_en: "Tabuk", name_ar: "تبوك" },
  { region_code: "SA-07", name_en: "Al-Wajh", name_ar: "الوجه" },
  { region_code: "SA-07", name_en: "Duba", name_ar: "ضباء" },
  { region_code: "SA-07", name_en: "Tayma", name_ar: "تيماء" },
  { region_code: "SA-07", name_en: "Umluj", name_ar: "أملج" },
  { region_code: "SA-07", name_en: "Haql", name_ar: "حقل" },
  { region_code: "SA-07", name_en: "Al-Bad'a", name_ar: "البدع" },
  { region_code: "SA-06", name_en: "Hail", name_ar: "حائل" },
  { region_code: "SA-06", name_en: "Baqaa", name_ar: "بقعاء" },
  { region_code: "SA-06", name_en: "Al-Ghazalah", name_ar: "الغزالة" },
  { region_code: "SA-06", name_en: "Al-Shinan", name_ar: "الشنان" },
  { region_code: "SA-06", name_en: "Al-Hait", name_ar: "الحائط" },
  { region_code: "SA-06", name_en: "Al-Sulaimi", name_ar: "السليمي" },
  { region_code: "SA-06", name_en: "Ash Shamli", name_ar: "الشملي" },
  { region_code: "SA-06", name_en: "Mawqaq", name_ar: "موقق" },
  { region_code: "SA-06", name_en: "Sumaira'a", name_ar: "سميراء" },
  { region_code: "SA-06", name_en: "Jubbah", name_ar: "جبة" },
  { region_code: "SA-06", name_en: "Al-Ajfar", name_ar: "الأجفر" },
  { region_code: "SA-12", name_en: "Skaka", name_ar: "سكاكا" },
  { region_code: "SA-12", name_en: "Dumat Al-Jandal", name_ar: "دومة الجندل" },
  { region_code: "SA-12", name_en: "Ghutti", name_ar: "غطي" },
  { region_code: "SA-12", name_en: "Mayqu", name_ar: "ميقوع" },
  { region_code: "SA-12", name_en: "Al-Fayyadh", name_ar: "الفياض" },
  { region_code: "SA-12", name_en: "Abu Ajram", name_ar: "أبو عجرم" },
  { region_code: "SA-12", name_en: "Suwayr", name_ar: "صوير" },
  { region_code: "SA-12", name_en: "Tubarjal", name_ar: "طبرجل" },
  { region_code: "SA-12", name_en: "Al-Jouf", name_ar: "الجوف" },
  { region_code: "SA-08", name_en: "Arar", name_ar: "عرعر" },
  { region_code: "SA-08", name_en: "Rafha", name_ar: "رفحاء" },
  { region_code: "SA-08", name_en: "Turaif", name_ar: "طريف" },
  { region_code: "SA-08", name_en: "Al-Uwayqilah", name_ar: "العويقيلة" },
  { region_code: "SA-08", name_en: "Al-Qurayyat", name_ar: "القريات" },
  { region_code: "SA-09", name_en: "Jizan", name_ar: "جيزان" },
  { region_code: "SA-09", name_en: "Sabya", name_ar: "صبيا" },
  { region_code: "SA-09", name_en: "Abu Arish", name_ar: "أبو عريش" },
  { region_code: "SA-09", name_en: "Samtah", name_ar: "صامطة" },
  { region_code: "SA-09", name_en: "Baish", name_ar: "بيش" },
  { region_code: "SA-09", name_en: "Al-Darb", name_ar: "الدرب" },
  { region_code: "SA-09", name_en: "Al-Khobh", name_ar: "الخوبة" },
  { region_code: "SA-09", name_en: "Damad", name_ar: "ضمد" },
  { region_code: "SA-09", name_en: "Al-Reeth", name_ar: "الريث" },
  { region_code: "SA-09", name_en: "Farasan", name_ar: "فرسان" },
  { region_code: "SA-09", name_en: "Al-Dayer", name_ar: "الدائر" },
  { region_code: "SA-09", name_en: "Al-Aridhah", name_ar: "العارضة" },
  { region_code: "SA-09", name_en: "Ahad Al-Masarihah", name_ar: "أحد المسارحة" },
  { region_code: "SA-09", name_en: "Al-Edabi", name_ar: "العيدابي" },
  { region_code: "SA-09", name_en: "Fayfa", name_ar: "فيفاء" },
  { region_code: "SA-09", name_en: "Al-Jaradiyah", name_ar: "الجرادية" },
  { region_code: "SA-09", name_en: "Al-Husseini", name_ar: "الحسيني" },
  { region_code: "SA-09", name_en: "Al-Hasamah", name_ar: "الحصمة" },
  { region_code: "SA-09", name_en: "Al-Badi Al-Qurfi", name_ar: "البديع والقرفي" },
  { region_code: "SA-09", name_en: "Al-Kharish", name_ar: "الخارش" },
  { region_code: "SA-09", name_en: "Al-Kharadilah", name_ar: "الخرادلة" },
  { region_code: "SA-09", name_en: "Al-Khadra", name_ar: "الخضراء" },
  { region_code: "SA-09", name_en: "Al-Rakubah", name_ar: "الركوبة" },
  { region_code: "SA-09", name_en: "Ash-Shuqayri", name_ar: "الشقيري" },
  { region_code: "SA-09", name_en: "Ash-Shawajirah", name_ar: "الشواجرة" },
  { region_code: "SA-09", name_en: "Ad-Dabyah", name_ar: "الظبية" },
  { region_code: "SA-09", name_en: "Al-Usaylah", name_ar: "العسيلة" },
  { region_code: "SA-09", name_en: "Abu Al-Sidad", name_ar: "أبو السداد" },
  { region_code: "SA-09", name_en: "Abu Al-Sila", name_ar: "أبو السلع" },
  { region_code: "SA-09", name_en: "Al-Madaya", name_ar: "المضايا" },
  { region_code: "SA-09", name_en: "Al-Matan", name_ar: "المطعن" },
  { region_code: "SA-09", name_en: "Mahliyah", name_ar: "محلية" },
  { region_code: "SA-09", name_en: "Muzahhirah", name_ar: "مزهرة" },
  { region_code: "SA-09", name_en: "Masliyah", name_ar: "مسلية" },
  { region_code: "SA-09", name_en: "Hakimah", name_ar: "حاكمة" },
  { region_code: "SA-09", name_en: "Ramadah", name_ar: "رمادة" },
  { region_code: "SA-09", name_en: "Al-Tuwal", name_ar: "الطوال" },
  { region_code: "SA-09", name_en: "Harub", name_ar: "هروب" },
  { region_code: "SA-10", name_en: "Najran", name_ar: "نجران" },
  { region_code: "SA-10", name_en: "Sharurah", name_ar: "شرورة" },
  { region_code: "SA-10", name_en: "Hubuna", name_ar: "حبونا" },
  { region_code: "SA-10", name_en: "Badr Al-Janub", name_ar: "بدر الجنوب" },
  { region_code: "SA-10", name_en: "Al-Wadiah", name_ar: "الوديعة" },
  { region_code: "SA-10", name_en: "Al-Mashaliyah", name_ar: "المشعلية" },
  { region_code: "SA-10", name_en: "Yadamah", name_ar: "يدمة" },
  { region_code: "SA-10", name_en: "Thar", name_ar: "ثار" },
  { region_code: "SA-10", name_en: "Khubash", name_ar: "خباش" },
  { region_code: "SA-10", name_en: "Al-Karkeer", name_ar: "الخرخير" },
  { region_code: "SA-11", name_en: "Al-Ardiyat", name_ar: "العرضيات" },
  { region_code: "SA-11", name_en: "Al-Bahah", name_ar: "الباحة" },
  { region_code: "SA-11", name_en: "Baljurashi", name_ar: "بلجرشي" },
  { region_code: "SA-11", name_en: "Al-Mandaq", name_ar: "المندق" },
  { region_code: "SA-11", name_en: "Al-Makhwah", name_ar: "المخواة" },
  { region_code: "SA-11", name_en: "Qilwah", name_ar: "قلوة" },
  { region_code: "SA-11", name_en: "Al-Aqiq", name_ar: "العقيق" },
  { region_code: "SA-11", name_en: "Al-Qura", name_ar: "القرى" },
  { region_code: "SA-11", name_en: "Gamed Alznad", name_ar: "غامد الزناد" },
  { region_code: "SA-11", name_en: "Al-Hajrah", name_ar: "الحجرة‎" },
  { region_code: "SA-11", name_en: "Bani Hasan", name_ar: "بني حسن" },
  { region_code: "SA-05", name_en: "Buraydah", name_ar: "بريدة" },
  { region_code: "SA-05", name_en: "Unayzah", name_ar: "عنيزة" },
  { region_code: "SA-05", name_en: "Ar Rass", name_ar: "الرس" },
  { region_code: "SA-05", name_en: "Al-Mithnab", name_ar: "المذنب" },
  { region_code: "SA-05", name_en: "Al-Bukayriyah", name_ar: "البكيرية" },
  { region_code: "SA-05", name_en: "Al-Badayea", name_ar: "البدائع" },
  { region_code: "SA-05", name_en: "Al-Asyah", name_ar: "الأسياح" },
  { region_code: "SA-05", name_en: "Al-Nabhaniyah", name_ar: "النبهانية" },
  { region_code: "SA-05", name_en: "Al-Shimasiyah", name_ar: "الشيحية" },
  { region_code: "SA-05", name_en: "Uyun Al-Jiwa", name_ar: "عيون الجواء" },
  { region_code: "SA-05", name_en: "Riyadh Al-Khabra", name_ar: "رياض الخبراء" },
  { region_code: "SA-05", name_en: "Uglat Asugour", name_ar: "عقلة الصقور" },
  { region_code: "SA-05", name_en: "Ash-Shiqqah Al-Ulya", name_ar: "الشقة العليا" },
  { region_code: "SA-05", name_en: "Al-Qawarah", name_ar: "القوارة" },
  { region_code: "SA-05", name_en: "Ash-Shimasiyah", name_ar: "الشماسية" },
  { region_code: "SA-05", name_en: "Al-Khabra", name_ar: "الخبراء" },
  { region_code: "SA-05", name_en: "Dariyah", name_ar: "ضرية" },
  { region_code: "SA-05", name_en: "Al-Mulayda", name_ar: "المليداء" },
  { region_code: "SA-05", name_en: "Al-Hilaliyah", name_ar: "الهلالية" },
  { region_code: "SA-05", name_en: "Dukhnah", name_ar: "دخنة" },
  { region_code: "SA-05", name_en: "Qubba", name_ar: "قبة" },
  { region_code: "SA-05", name_en: "Ayn Ibn Fuhayd", name_ar: "عين بن فهيد" },
  { name_en: "Other", name_ar: "أخرى" }
]

cities.each do |city|
  next if city[:region_code].blank?

  region = Region.find_by!(code: city[:region_code])

  City.create!(
    name_en: city[:name_en],
    name_ar: city[:name_ar],
    region: region
  )
end
