countries = [
  { name_en: "Afghanistan", name_ar: "أفغانستان", code: "AF" },
  { name_en: "Åland Islands", name_ar: "جزر آلاند", code: "AX" },
  { name_en: "Albania", name_ar: "ألبانيا", code: "AL" },
  { name_en: "Algeria", name_ar: "الجزائر", code: "DZ" },
  { name_en: "American Samoa", name_ar: "ساموا الأمريكية", code: "AS" },
  { name_en: "Andorra", name_ar: "أندورا", code: "AD" },
  { name_en: "Angola", name_ar: "أنغولا", code: "AO" },
  { name_en: "Anguilla", name_ar: "أنغويلا", code: "AI" },
  { name_en: "Antarctica", name_ar: "القارة القطبية الجنوبية", code: "AQ" },
  { name_en: "Antigua and Barbuda", name_ar: "أنتيغوا وبربودا", code: "AG" },
  { name_en: "Argentina", name_ar: "الأرجنتين", code: "AR" },
  { name_en: "Armenia", name_ar: "أرمينيا", code: "AM" },
  { name_en: "Aruba", name_ar: "أروبا", code: "AW" },
  { name_en: "Australia", name_ar: "أستراليا", code: "AU" },
  { name_en: "Austria", name_ar: "النمسا", code: "AT" },
  { name_en: "Azerbaijan", name_ar: "أذربيجان", code: "AZ" },
  { name_en: "Bahamas", name_ar: "الباهاما", code: "BS" },
  { name_en: "Bahrain", name_ar: "البحرين", code: "BH" },
  { name_en: "Bangladesh", name_ar: "بنغلاديش", code: "BD" },
  { name_en: "Barbados", name_ar: "بربادوس", code: "BB" },
  { name_en: "Belarus", name_ar: "بيلاروسيا", code: "BY" },
  { name_en: "Belgium", name_ar: "بلجيكا", code: "BE" },
  { name_en: "Belize", name_ar: "بليز", code: "BZ" },
  { name_en: "Benin", name_ar: "بنين", code: "BJ" },
  { name_en: "Bermuda", name_ar: "برمودا", code: "BM" },
  { name_en: "Bhutan", name_ar: "بوتان", code: "BT" },
  { name_en: "Bolivia", name_ar: "بوليفيا", code: "BO" },
  { name_en: "Bonaire, Sint Eustatius and Saba", name_ar: "بونير وسينت أوستاتيوس وسابا", code: "BQ" },
  { name_en: "Bosnia and Herzegovina", name_ar: "البوسنة والهرسك", code: "BA" },
  { name_en: "Botswana", name_ar: "بوتسوانا", code: "BW" },
  { name_en: "Bouvet Island", name_ar: "جزيرة بوفيه", code: "BV" },
  { name_en: "Brazil", name_ar: "البرازيل", code: "BR" },
  { name_en: "British Indian Ocean Territory", name_ar: "إقليم المحيط الهندي البريطاني", code: "IO" },
  { name_en: "Brunei", name_ar: "بروناي", code: "BN" },
  { name_en: "Bulgaria", name_ar: "بلغاريا", code: "BG" },
  { name_en: "Burkina Faso", name_ar: "بوركينا فاسو", code: "BF" },
  { name_en: "Burundi", name_ar: "بوروندي", code: "BI" },
  { name_en: "Cabo Verde", name_ar: "الرأس الأخضر", code: "CV" },
  { name_en: "Cambodia", name_ar: "كمبوديا", code: "KH" },
  { name_en: "Cameroon", name_ar: "الكاميرون", code: "CM" },
  { name_en: "Canada", name_ar: "كندا", code: "CA" },
  { name_en: "Cayman Islands", name_ar: "جزر كايمان", code: "KY" },
  { name_en: "Central African Republic", name_ar: "جمهورية أفريقيا الوسطى", code: "CF" },
  { name_en: "Chad", name_ar: "تشاد", code: "TD" },
  { name_en: "Chile", name_ar: "تشيلي", code: "CL" },
  { name_en: "China", name_ar: "الصين", code: "CN" },
  { name_en: "Christmas Island", name_ar: "جزيرة كريسماس", code: "CX" },
  { name_en: "Cocos (Keeling) Islands", name_ar: "جزر كوكوس (كيلينغ)", code: "CC" },
  { name_en: "Colombia", name_ar: "كولومبيا", code: "CO" },
  { name_en: "Comoros", name_ar: "جزر القمر", code: "KM" },
  { name_en: "Congo", name_ar: "الكونغو", code: "CG" },
  { name_en: "Congo, Democratic Republic of the", name_ar: "جمهورية الكونغو الديمقراطية", code: "CD" },
  { name_en: "Cook Islands", name_ar: "جزر كوك", code: "CK" },
  { name_en: "Costa Rica", name_ar: "كوستاريكا", code: "CR" },
  { name_en: "Côte d'Ivoire", name_ar: "ساحل العاج", code: "CI" },
  { name_en: "Croatia", name_ar: "كرواتيا", code: "HR" },
  { name_en: "Cuba", name_ar: "كوبا", code: "CU" },
  { name_en: "Curaçao", name_ar: "كوراساو", code: "CW" },
  { name_en: "Cyprus", name_ar: "قبرص", code: "CY" },
  { name_en: "Czechia", name_ar: "التشيك", code: "CZ" },
  { name_en: "Denmark", name_ar: "الدنمارك", code: "DK" },
  { name_en: "Djibouti", name_ar: "جيبوتي", code: "DJ" },
  { name_en: "Dominica", name_ar: "دومينيكا", code: "DM" },
  { name_en: "Dominican Republic", name_ar: "جمهورية الدومينيكان", code: "DO" },
  { name_en: "Ecuador", name_ar: "الإكوادور", code: "EC" },
  { name_en: "Egypt", name_ar: "مصر", code: "EG" },
  { name_en: "El Salvador", name_ar: "السلفادور", code: "SV" },
  { name_en: "Equatorial Guinea", name_ar: "غينيا الاستوائية", code: "GQ" },
  { name_en: "Eritrea", name_ar: "إريتريا", code: "ER" },
  { name_en: "Estonia", name_ar: "إستونيا", code: "EE" },
  { name_en: "Eswatini", name_ar: "إسواتيني", code: "SZ" },
  { name_en: "Ethiopia", name_ar: "إثيوبيا", code: "ET" },
  { name_en: "Falkland Islands", name_ar: "جزر فوكلاند", code: "FK" },
  { name_en: "Faroe Islands", name_ar: "جزر فارو", code: "FO" },
  { name_en: "Fiji", name_ar: "فيجي", code: "FJ" },
  { name_en: "Finland", name_ar: "فنلندا", code: "FI" },
  { name_en: "France", name_ar: "فرنسا", code: "FR" },
  { name_en: "French Guiana", name_ar: "غويانا الفرنسية", code: "GF" },
  { name_en: "French Polynesia", name_ar: "بولينيزيا الفرنسية", code: "PF" },
  { name_en: "French Southern Territories", name_ar: "الأقاليم الجنوبية الفرنسية", code: "TF" },
  { name_en: "Gabon", name_ar: "الغابون", code: "GA" },
  { name_en: "Gambia", name_ar: "غامبيا", code: "GM" },
  { name_en: "Georgia", name_ar: "جورجيا", code: "GE" },
  { name_en: "Germany", name_ar: "ألمانيا", code: "DE" },
  { name_en: "Ghana", name_ar: "غانا", code: "GH" },
  { name_en: "Gibraltar", name_ar: "جبل طارق", code: "GI" },
  { name_en: "Greece", name_ar: "اليونان", code: "GR" },
  { name_en: "Greenland", name_ar: "غرينلاند", code: "GL" },
  { name_en: "Grenada", name_ar: "غرينادا", code: "GD" },
  { name_en: "Guadeloupe", name_ar: "غوادلوب", code: "GP" },
  { name_en: "Guam", name_ar: "غوام", code: "GU" },
  { name_en: "Guatemala", name_ar: "غواتيمالا", code: "GT" },
  { name_en: "Guernsey", name_ar: "غيرنزي", code: "GG" },
  { name_en: "Guinea", name_ar: "غينيا", code: "GN" },
  { name_en: "Guinea-Bissau", name_ar: "غينيا بيساو", code: "GW" },
  { name_en: "Guyana", name_ar: "غيانا", code: "GY" },
  { name_en: "Haiti", name_ar: "هايتي", code: "HT" },
  { name_en: "Heard Island and McDonald Islands", name_ar: "جزيرة هيرد وجزر ماكدونالد", code: "HM" },
  { name_en: "Holy See", name_ar: "الكرسي الرسولي", code: "VA" },
  { name_en: "Honduras", name_ar: "هندوراس", code: "HN" },
  { name_en: "Hong Kong", name_ar: "هونغ كونغ", code: "HK" },
  { name_en: "Hungary", name_ar: "المجر", code: "HU" },
  { name_en: "Iceland", name_ar: "آيسلندا", code: "IS" },
  { name_en: "India", name_ar: "الهند", code: "IN" },
  { name_en: "Indonesia", name_ar: "إندونيسيا", code: "ID" },
  { name_en: "Iran", name_ar: "إيران", code: "IR" },
  { name_en: "Iraq", name_ar: "العراق", code: "IQ" },
  { name_en: "Ireland", name_ar: "أيرلندا", code: "IE" },
  { name_en: "Isle of Man", name_ar: "جزيرة مان", code: "IM" },
  { name_en: "Israel", name_ar: "إسرائيل", code: "IL" },
  { name_en: "Italy", name_ar: "إيطاليا", code: "IT" },
  { name_en: "Jamaica", name_ar: "جامايكا", code: "JM" },
  { name_en: "Japan", name_ar: "اليابان", code: "JP" },
  { name_en: "Jersey", name_ar: "جيرزي", code: "JE" },
  { name_en: "Jordan", name_ar: "الأردن", code: "JO" },
  { name_en: "Kazakhstan", name_ar: "كازاخستان", code: "KZ" },
  { name_en: "Kenya", name_ar: "كينيا", code: "KE" },
  { name_en: "Kiribati", name_ar: "كيريباتي", code: "KI" },
  { name_en: "Korea, Democratic People's Republic of", name_ar: "كوريا الشمالية", code: "KP" },
  { name_en: "Korea, Republic of", name_ar: "كوريا الجنوبية", code: "KR" },
  { name_en: "Kuwait", name_ar: "الكويت", code: "KW" },
  { name_en: "Kyrgyzstan", name_ar: "قيرغيزستان", code: "KG" },
  { name_en: "Lao People's Democratic Republic", name_ar: "لاوس", code: "LA" },
  { name_en: "Latvia", name_ar: "لاتفيا", code: "LV" },
  { name_en: "Lebanon", name_ar: "لبنان", code: "LB" },
  { name_en: "Lesotho", name_ar: "ليسوتو", code: "LS" },
  { name_en: "Liberia", name_ar: "ليبيريا", code: "LR" },
  { name_en: "Libya", name_ar: "ليبيا", code: "LY" },
  { name_en: "Liechtenstein", name_ar: "ليختنشتاين", code: "LI" },
  { name_en: "Lithuania", name_ar: "ليتوانيا", code: "LT" },
  { name_en: "Luxembourg", name_ar: "لوكسمبورغ", code: "LU" },
  { name_en: "Macao", name_ar: "ماكاو", code: "MO" },
  { name_en: "Madagascar", name_ar: "مدغشقر", code: "MG" },
  { name_en: "Malawi", name_ar: "ملاوي", code: "MW" },
  { name_en: "Malaysia", name_ar: "ماليزيا", code: "MY" },
  { name_en: "Maldives", name_ar: "المالديف", code: "MV" },
  { name_en: "Mali", name_ar: "مالي", code: "ML" },
  { name_en: "Malta", name_ar: "مالطا", code: "MT" },
  { name_en: "Marshall Islands", name_ar: "جزر مارشال", code: "MH" },
  { name_en: "Martinique", name_ar: "مارتينيك", code: "MQ" },
  { name_en: "Mauritania", name_ar: "موريتانيا", code: "MR" },
  { name_en: "Mauritius", name_ar: "موريشيوس", code: "MU" },
  { name_en: "Mayotte", name_ar: "مايوت", code: "YT" },
  { name_en: "Mexico", name_ar: "المكسيك", code: "MX" },
  { name_en: "Micronesia, Federated States of", name_ar: "ولايات ميكرونيزيا المتحدة", code: "FM" },
  { name_en: "Moldova", name_ar: "مولدوفا", code: "MD" },
  { name_en: "Monaco", name_ar: "موناكو", code: "MC" },
  { name_en: "Mongolia", name_ar: "منغوليا", code: "MN" },
  { name_en: "Montenegro", name_ar: "الجبل الأسود", code: "ME" },
  { name_en: "Montserrat", name_ar: "مونتسرات", code: "MS" },
  { name_en: "Morocco", name_ar: "المغرب", code: "MA" },
  { name_en: "Mozambique", name_ar: "موزمبيق", code: "MZ" },
  { name_en: "Myanmar", name_ar: "ميانمار", code: "MM" },
  { name_en: "Namibia", name_ar: "ناميبيا", code: "NA" },
  { name_en: "Nauru", name_ar: "ناورو", code: "NR" },
  { name_en: "Nepal", name_ar: "نيبال", code: "NP" },
  { name_en: "Netherlands", name_ar: "هولندا", code: "NL" },
  { name_en: "New Caledonia", name_ar: "كاليدونيا الجديدة", code: "NC" },
  { name_en: "New Zealand", name_ar: "نيوزيلندا", code: "NZ" },
  { name_en: "Nicaragua", name_ar: "نيكاراغوا", code: "NI" },
  { name_en: "Niger", name_ar: "النيجر", code: "NE" },
  { name_en: "Nigeria", name_ar: "نيجيريا", code: "NG" },
  { name_en: "Niue", name_ar: "نيوي", code: "NU" },
  { name_en: "Norfolk Island", name_ar: "جزيرة نورفولك", code: "NF" },
  { name_en: "North Macedonia", name_ar: "مقدونيا الشمالية", code: "MK" },
  { name_en: "Northern Mariana Islands", name_ar: "جزر ماريانا الشمالية", code: "MP" },
  { name_en: "Norway", name_ar: "النرويج", code: "NO" },
  { name_en: "Oman", name_ar: "عُمان", code: "OM" },
  { name_en: "Pakistan", name_ar: "باكستان", code: "PK" },
  { name_en: "Palau", name_ar: "بالاو", code: "PW" },
  { name_en: "Palestine, State of", name_ar: "دولة فلسطين", code: "PS" },
  { name_en: "Panama", name_ar: "بنما", code: "PA" },
  { name_en: "Papua New Guinea", name_ar: "بابوا غينيا الجديدة", code: "PG" },
  { name_en: "Paraguay", name_ar: "باراغواي", code: "PY" },
  { name_en: "Peru", name_ar: "بيرو", code: "PE" },
  { name_en: "Philippines", name_ar: "الفلبين", code: "PH" },
  { name_en: "Pitcairn", name_ar: "جزر بيتكيرن", code: "PN" },
  { name_en: "Poland", name_ar: "بولندا", code: "PL" },
  { name_en: "Portugal", name_ar: "البرتغال", code: "PT" },
  { name_en: "Puerto Rico", name_ar: "بورتوريكو", code: "PR" },
  { name_en: "Qatar", name_ar: "قطر", code: "QA" },
  { name_en: "Réunion", name_ar: "ريونيون", code: "RE" },
  { name_en: "Romania", name_ar: "رومانيا", code: "RO" },
  { name_en: "Russian Federation", name_ar: "روسيا", code: "RU" },
  { name_en: "Rwanda", name_ar: "رواندا", code: "RW" },
  { name_en: "Saint Barthélemy", name_ar: "سان بارتليمي", code: "BL" },
  { name_en: "Saint Helena, Ascension and Tristan da Cunha", name_ar: "سانت هيلينا وأسينشين وتريستان دا كونا", code: "SH" },
  { name_en: "Saint Kitts and Nevis", name_ar: "سانت كيتس ونيفيس", code: "KN" },
  { name_en: "Saint Lucia", name_ar: "سانت لوسيا", code: "LC" },
  { name_en: "Saint Martin (French part)", name_ar: "سان مارتن (الجزء الفرنسي)", code: "MF" },
  { name_en: "Saint Pierre and Miquelon", name_ar: "سان بيير وميكلون", code: "PM" },
  { name_en: "Saint Vincent and the Grenadines", name_ar: "سانت فنسنت والغرينادين", code: "VC" },
  { name_en: "Samoa", name_ar: "ساموا", code: "WS" },
  { name_en: "San Marino", name_ar: "سان مارينو", code: "SM" },
  { name_en: "Sao Tome and Principe", name_ar: "ساو تومي وبرينسيبي", code: "ST" },
  { name_en: "Saudi Arabia", name_ar: "المملكة العربية السعودية", code: "SA" },
  { name_en: "Senegal", name_ar: "السنغال", code: "SN" },
  { name_en: "Serbia", name_ar: "صربيا", code: "RS" },
  { name_en: "Seychelles", name_ar: "سيشل", code: "SC" },
  { name_en: "Sierra Leone", name_ar: "سيراليون", code: "SL" },
  { name_en: "Singapore", name_ar: "سنغافورة", code: "SG" },
  { name_en: "Sint Maarten (Dutch part)", name_ar: "سانت مارتن (الجزء الهولندي)", code: "SX" },
  { name_en: "Slovakia", name_ar: "سلوفاكيا", code: "SK" },
  { name_en: "Slovenia", name_ar: "سلوفينيا", code: "SI" },
  { name_en: "Solomon Islands", name_ar: "جزر سليمان", code: "SB" },
  { name_en: "Somalia", name_ar: "الصومال", code: "SO" },
  { name_en: "South Africa", name_ar: "جنوب أفريقيا", code: "ZA" },
  { name_en: "South Georgia and the South Sandwich Islands", name_ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", code: "GS" },
  { name_en: "South Sudan", name_ar: "جنوب السودان", code: "SS" },
  { name_en: "Spain", name_ar: "إسبانيا", code: "ES" },
  { name_en: "Sri Lanka", name_ar: "سريلانكا", code: "LK" },
  { name_en: "Sudan", name_ar: "السودان", code: "SD" },
  { name_en: "Suriname", name_ar: "سورينام", code: "SR" },
  { name_en: "Svalbard and Jan Mayen", name_ar: "سفالبارد ويان ماين", code: "SJ" },
  { name_en: "Sweden", name_ar: "السويد", code: "SE" },
  { name_en: "Switzerland", name_ar: "سويسرا", code: "CH" },
  { name_en: "Syrian Arab Republic", name_ar: "سوريا", code: "SY" },
  { name_en: "Taiwan", name_ar: "تايوان", code: "TW" },
  { name_en: "Tajikistan", name_ar: "طاجيكستان", code: "TJ" },
  { name_en: "Tanzania", name_ar: "تنزانيا", code: "TZ" },
  { name_en: "Thailand", name_ar: "تايلاند", code: "TH" },
  { name_en: "Timor-Leste", name_ar: "تيمور الشرقية", code: "TL" },
  { name_en: "Togo", name_ar: "توجو", code: "TG" },
  { name_en: "Tokelau", name_ar: "توكيلاو", code: "TK" },
  { name_en: "Tonga", name_ar: "تونغا", code: "TO" },
  { name_en: "Trinidad and Tobago", name_ar: "ترينيداد وتوباغو", code: "TT" },
  { name_en: "Tunisia", name_ar: "تونس", code: "TN" },
  { name_en: "Türkiye", name_ar: "تركيا", code: "TR" },
  { name_en: "Turkmenistan", name_ar: "تركمانستان", code: "TM" },
  { name_en: "Turks and Caicos Islands", name_ar: "جزر توركس وكايكوس", code: "TC" },
  { name_en: "Tuvalu", name_ar: "توفالو", code: "TV" },
  { name_en: "Uganda", name_ar: "أوغندا", code: "UG" },
  { name_en: "Ukraine", name_ar: "أوكرانيا", code: "UA" },
  { name_en: "United Arab Emirates", name_ar: "الإمارات العربية المتحدة", code: "AE" },
  { name_en: "United Kingdom", name_ar: "المملكة المتحدة", code: "GB" },
  { name_en: "United States", name_ar: "الولايات المتحدة", code: "US" },
  { name_en: "United States Minor Outlying Islands", name_ar: "جزر الولايات المتحدة الصغيرة النائية", code: "UM" },
  { name_en: "Uruguay", name_ar: "أوروغواي", code: "UY" },
  { name_en: "Uzbekistan", name_ar: "أوزبكستان", code: "UZ" },
  { name_en: "Vanuatu", name_ar: "فانواتو", code: "VU" },
  { name_en: "Venezuela", name_ar: "فنزويلا", code: "VE" },
  { name_en: "Viet Nam", name_ar: "فيتنام", code: "VN" },
  { name_en: "Virgin Islands, British", name_ar: "جزر العذراء البريطانية", code: "VG" },
  { name_en: "Virgin Islands, U.S.", name_ar: "جزر العذراء الأمريكية", code: "VI" },
  { name_en: "Wallis and Futuna", name_ar: "واليس وفوتونا", code: "WF" },
  { name_en: "Western Sahara", name_ar: "الصحراء الغربية", code: "EH" },
  { name_en: "Yemen", name_ar: "اليمن", code: "YE" },
  { name_en: "Zambia", name_ar: "زامبيا", code: "ZM" },
  { name_en: "Zimbabwe", name_ar: "زيمبابوي", code: "ZW" }
]

countries.each do |country|
  Country.create!(
    name_en: country[:name_en],
    name_ar: country[:name_ar],
    code: country[:code]
  )
end
