vehicle_makes = [
  { "name_en": "AC", "name_ar": "اي سي" },
  { "name_en": "ALPINA", "name_ar": "البينا" },
  { "name_en": "ALPINE", "name_ar": "الباين" },
  { "name_en": "ALVIS", "name_ar": "الفيس" },
  { "name_en": "AUDI", "name_ar": "اودي" },
  { "name_en": "BENTLEY", "name_ar": "بنتلي" },
  { "name_en": "BMW", "name_ar": "بي ام دبليو" },
  { "name_en": "BUGATTI", "name_ar": "بوغاتي" },
  { "name_en": "BUICK", "name_ar": "بيوك" },
  { "name_en": "CATERHAM", "name_ar": "كاترهام" },
  { "name_en": "DAEWOO", "name_ar": "دايو" },
  { "name_en": "CITROEN", "name_ar": "سيتروين" },
  { "name_en": "DAIHATSU", "name_ar": "ديهاتسو" },
  { "name_en": "DATSUN", "name_ar": "داتسون" },
  { "name_en": "FERRARI", "name_ar": "فيراري" },
  { "name_en": "FIAT", "name_ar": "فيات" },
  { "name_en": "FORD", "name_ar": "فورد" },
  { "name_en": "GAZ", "name_ar": "غاز" },
  { "name_en": "GEELY", "name_ar": "جيلي" },
  { "name_en": "HOLDEN", "name_ar": "هولدين" },
  { "name_en": "HUMMER", "name_ar": "همر" },
  { "name_en": "HYUNDAI", "name_ar": "هيونداي" },
  { "name_en": "ISUZU", "name_ar": "ايسوزو" },
  { "name_en": "JAGUAR", "name_ar": "جاغوار" },
  { "name_en": "LANCIA", "name_ar": "لانشيا" },
  { "name_en": "LEXUS", "name_ar": "لكزس" },
  { "name_en": "LOTUS", "name_ar": "لوتس" },
  { "name_en": "MASERATI", "name_ar": "مازيراتي" },
  { "name_en": "MCLAREN", "name_ar": "ماكلارين" },
  { "name_en": "MG", "name_ar": "ام جي" },
  { "name_en": "MORGAN", "name_ar": "مورغان" },
  { "name_en": "NISSAN", "name_ar": "نيسان" },
  { "name_en": "PEUGEOT", "name_ar": "بيجو" },
  { "name_en": "PININFARINA", "name_ar": "بينينفارينا" },
  { "name_en": "PORSCHE", "name_ar": "بورش" },
  { "name_en": "RENAULT", "name_ar": "رينو" },
  { "name_en": "SAAB", "name_ar": "ساب" },
  { "name_en": "SEAT", "name_ar": "سيات" },
  { "name_en": "SKODA", "name_ar": "سكودا" },
  { "name_en": "SUBARU", "name_ar": "سوبارو" },
  { "name_en": "SUZUKI", "name_ar": "سوزوكي" },
  { "name_en": "TATA", "name_ar": "تاتا" },
  { "name_en": "VAUXHALL", "name_ar": "فوكسهول" },
  { "name_en": "HONDA", "name_ar": "هوندا" },
  { "name_en": "KOENIGSEGG", "name_ar": "كوينيجسيج" },
  { "name_en": "CHEVROLET", "name_ar": "شيفورلية" },
  { "name_en": "CHRYSLER", "name_ar": "كرايسلر" },
  { "name_en": "CADILLAC", "name_ar": "كاديلاك" },
  { "name_en": "DODGE", "name_ar": "دودج" },
  { "name_en": "GMC", "name_ar": "جي ام سي" },
  { "name_en": "INFINITI", "name_ar": "انفينيتي" },
  { "name_en": "KIA", "name_ar": "كيا" },
  { "name_en": "LAMBORGHINI", "name_ar": "لامبورغيني" },
  { "name_en": "MAHINDRA", "name_ar": "ماهيندرا" },
  { "name_en": "MAYBACH", "name_ar": "مايباخ" },
  { "name_en": "MITSUBISHI", "name_ar": "ميتسوبيشي" },
  { "name_en": "OPEL", "name_ar": "أوبل" },
  { "name_en": "PROTON", "name_ar": "بروتون" },
  { "name_en": "SCION", "name_ar": "سايون" },
  { "name_en": "SSANGYONG", "name_ar": "سانغيونغ" },
  { "name_en": "TOYOTA", "name_ar": "تويوتا" },
  { "name_en": "TESLA", "name_ar": "تيسلا" },
  { "name_en": "ABARTH", "name_ar": "ابارث" },
  { "name_en": "ACURA", "name_ar": "اكيورا" },
  { "name_en": "AMC", "name_ar": "اى ام سي" },
  { "name_en": "JEEP", "name_ar": "جيب" },
  { "name_en": "LINCOLN", "name_ar": "لينكون" },
  { "name_en": "MAZDA", "name_ar": "مازدا" },
  { "name_en": "MERCURY", "name_ar": "ميركوري" },
  { "name_en": "MINI COOPER", "name_ar": "ميني كوبر" },
  { "name_en": "VOLKSWAGEN", "name_ar": "فولكس واجن" },
  { "name_en": "VOLVO", "name_ar": "فولفو" },
  { "name_en": "ALFA ROMEO", "name_ar": "الفا رمويو" },
  { "name_en": "ASTON MARTIN", "name_ar": "استون مارتن" },
  { "name_en": "LAND ROVER", "name_ar": "لاند روفر" },
  { "name_en": "ROLLS ROYCE", "name_ar": "رولز رويس" },
  { "name_en": "MERCEDES", "name_ar": "مرسيدس" },
  { "name_en": "POLARIS", "name_ar": "بولاريس" },
  { "name_en": "INDIAN", "name_ar": "انديان" },
  { "name_en": "VICTORY", "name_ar": "فيكتوري" },
  { "name_en": "HARLEY DEVIDSON", "name_ar": "هارلي ديفيدسون" },
  { "name_en": "CHANGAN", "name_ar": "شانجان" },
  { "name_en": "GAC", "name_ar": "جاك قوناو" },
  { "name_en": "JAC", "name_ar": "جاك" },
  { "name_en": "PONTIAC", "name_ar": "بونتياك" },
  { "name_en": "CHERY", "name_ar": "شيري" },
  { "name_en": "HINO", "name_ar": "هينو" },
  { "name_en": "OLDSMOBILE", "name_ar": "اولدزموبيل" },
  { "name_en": "FOTON", "name_ar": "فوتون" },
  { "name_en": "BYD", "name_ar": "بي واي دي" },
  { "name_en": "GREAT WALL", "name_ar": "جريت وال" },
  { "name_en": "FAW", "name_ar": "فاو" },
  { "name_en": "MOTORCYCLE", "name_ar": "دراجة نارية" },
  { "name_en": "HAVAL", "name_ar": "هافال" },
  { "name_en": "BAIC", "name_ar": "بايك" },
  { "name_en": "SAIC", "name_ar": "سايك" },
  { "name_en": "KAWASAKI", "name_ar": "كاواساكي" },
  { "name_en": "MAN", "name_ar": "مان" },
  { "name_en": "RANGE ROVER", "name_ar": "رنج روفر" },
  { "name_en": "GENESIS", "name_ar": "جينيسيس" },
  { "name_en": "SHANGHAI", "name_ar": "شانقهاي" },
  { "name_en": "JMC", "name_ar": "JMC" },
  { "name_en": "CMC", "name_ar": "سي ام سي" },
  { "name_en": "ASHOK LEYLAND", "name_ar": "أشوك ليلاند" },
  { "name_en": "DONGFENG", "name_ar": "دونج فينج" },
  { "name_en": "MAXUS", "name_ar": "ماكسيوس" },
  { "name_en": "JETOUR", "name_ar": "جيتور" },
  { "name_en": "LUCID", "name_ar": "لوسيد" },
  { "name_en": "SINOTRUK", "name_ar": "سينوترك" },
  { "name_en": "HUANGHAI", "name_ar": "هوانجاي" },
  { "name_en": "CITREON", "name_ar": "سيتريون" },
  { "name_en": "LYNK & CO", "name_ar": "لينك اند كو" },
  { "name_en": "HONGQI", "name_ar": "هونشي" },
  { "name_en": "SHACMAN", "name_ar": "شاكمان" },
  { "name_en": "SCANIA", "name_ar": "سكانيا" },
  { "name_en": "GWM", "name_ar": "جي دبليو ام" },
  { "name_en": "SHAANXI", "name_ar": "شانكسي" },
  { "name_en": "ZX AUTO", "name_ar": "زي اكس اوتو" },
  { "name_en": "UD TRUCKS", "name_ar": "شاحنات يو دي" },
  { "name_en": "ANKAI", "name_ar": "انكاي" },
  { "name_en": "KING LONG", "name_ar": "كنق لونق" },
  { "name_en": "IVECO", "name_ar": "ايفيكو" },
  { "name_en": "GRAND TIGER", "name_ar": "قراند تايقر" },
  { "name_en": "SANY", "name_ar": "ساني" },
  { "name_en": "INTERNATIONAL", "name_ar": "انترناشيونال" },
  { "name_en": "CNHTC", "name_ar": "سي إن إتش تي سي" },
  { "name_en": "MATHIEU", "name_ar": "ماثيو" },
  { "name_en": "ZOTYE", "name_ar": "زوتي" },
  { "name_en": "JCB", "name_ar": "JCB" },
  { "name_en": "JAECOO", "name_ar": "JAECOO" },
  { "name_en": "HIGER", "name_ar": "HIGER" },
  { "name_en": "BOBCAT", "name_ar": "BOBCAT" },
  { "name_en": "BLK", "name_ar": "BLK" },
  { "name_en": "ZHONG TONG", "name_ar": "ZHONG TONG" },
  { "name_en": "تيدر", "name_ar": "تيدر" },
  { "name_en": "SHOVEL", "name_ar": "شيول" },
  { "name_en": "SEDAN", "name_ar": "سيدان" },
  { "name_en": "OTHER", "name_ar": "أخرى" }
]

vehicle_makes.each do |vehicle_make|
  VehicleMake.create!(
    name_en: vehicle_make[:name_en],
    name_ar: vehicle_make[:name_ar]
  )
end
