vehicle_makes = [
  { "id": 1, "name_en": "AC", "name_ar": "اي سي" },
  { "id": 2, "name_en": "ALPINA", "name_ar": "البينا" },
  { "id": 3, "name_en": "ALPINE", "name_ar": "الباين" },
  { "id": 4, "name_en": "ALVIS", "name_ar": "الفيس" },
  { "id": 5, "name_en": "AUDI", "name_ar": "اودي" },
  { "id": 6, "name_en": "BENTLEY", "name_ar": "بنتلي" },
  { "id": 7, "name_en": "BMW", "name_ar": "بي ام دبليو" },
  { "id": 8, "name_en": "BUGATTI", "name_ar": "بوغاتي" },
  { "id": 9, "name_en": "BUICK", "name_ar": "بيوك" },
  { "id": 10, "name_en": "CATERHAM", "name_ar": "كاترهام" },
  { "id": 11, "name_en": "DAEWOO", "name_ar": "دايو" },
  { "id": 12, "name_en": "CITROEN", "name_ar": "سيتروين" },
  { "id": 13, "name_en": "DAIHATSU", "name_ar": "ديهاتسو" },
  { "id": 14, "name_en": "DATSUN", "name_ar": "داتسون" },
  { "id": 15, "name_en": "FERRARI", "name_ar": "فيراري" },
  { "id": 16, "name_en": "FIAT", "name_ar": "فيات" },
  { "id": 17, "name_en": "FORD", "name_ar": "فورد" },
  { "id": 18, "name_en": "GAZ", "name_ar": "غاز" },
  { "id": 19, "name_en": "GEELY", "name_ar": "جيلي" },
  { "id": 20, "name_en": "HOLDEN", "name_ar": "هولدين" },
  { "id": 21, "name_en": "HUMMER", "name_ar": "همر" },
  { "id": 22, "name_en": "HYUNDAI", "name_ar": "هيونداي" },
  { "id": 23, "name_en": "ISUZU", "name_ar": "ايسوزو" },
  { "id": 24, "name_en": "JAGUAR", "name_ar": "جاغوار" },
  { "id": 25, "name_en": "LANCIA", "name_ar": "لانشيا" },
  { "id": 26, "name_en": "LEXUS", "name_ar": "لكزس" },
  { "id": 27, "name_en": "LOTUS", "name_ar": "لوتس" },
  { "id": 28, "name_en": "MASERATI", "name_ar": "مازيراتي" },
  { "id": 29, "name_en": "MCLAREN", "name_ar": "ماكلارين" },
  { "id": 30, "name_en": "MG", "name_ar": "ام جي" },
  { "id": 31, "name_en": "MORGAN", "name_ar": "مورغان" },
  { "id": 32, "name_en": "NISSAN", "name_ar": "نيسان" },
  { "id": 33, "name_en": "PEUGEOT", "name_ar": "بيجو" },
  { "id": 34, "name_en": "PININFARINA", "name_ar": "بينينفارينا" },
  { "id": 35, "name_en": "PORSCHE", "name_ar": "بورش" },
  { "id": 36, "name_en": "RENAULT", "name_ar": "رينو" },
  { "id": 37, "name_en": "SAAB", "name_ar": "ساب" },
  { "id": 38, "name_en": "SEAT", "name_ar": "سيات" },
  { "id": 39, "name_en": "SKODA", "name_ar": "سكودا" },
  { "id": 40, "name_en": "SUBARU", "name_ar": "سوبارو" },
  { "id": 41, "name_en": "SUZUKI", "name_ar": "سوزوكي" },
  { "id": 42, "name_en": "TATA", "name_ar": "تاتا" },
  { "id": 43, "name_en": "VAUXHALL", "name_ar": "فوكسهول" },
  { "id": 44, "name_en": "HONDA", "name_ar": "هوندا" },
  { "id": 45, "name_en": "KOENIGSEGG", "name_ar": "كوينيجسيج" },
  { "id": 46, "name_en": "CHEVROLET", "name_ar": "شيفورلية" },
  { "id": 47, "name_en": "CHRYSLER", "name_ar": "كرايسلر" },
  { "id": 48, "name_en": "CADILLAC", "name_ar": "كاديلاك" },
  { "id": 49, "name_en": "DODGE", "name_ar": "دودج" },
  { "id": 50, "name_en": "GMC", "name_ar": "جي ام سي" },
  { "id": 51, "name_en": "INFINITI", "name_ar": "انفينيتي" },
  { "id": 52, "name_en": "KIA", "name_ar": "كيا" },
  { "id": 53, "name_en": "LAMBORGHINI", "name_ar": "لامبورغيني" },
  { "id": 54, "name_en": "MAHINDRA", "name_ar": "ماهيندرا" },
  { "id": 55, "name_en": "MAYBACH", "name_ar": "مايباخ" },
  { "id": 56, "name_en": "MITSUBISHI", "name_ar": "ميتسوبيشي" },
  { "id": 57, "name_en": "OPEL", "name_ar": "أوبل" },
  { "id": 58, "name_en": "PROTON", "name_ar": "بروتون" },
  { "id": 59, "name_en": "SCION", "name_ar": "سايون" },
  { "id": 60, "name_en": "SSANGYONG", "name_ar": "سانغيونغ" },
  { "id": 61, "name_en": "TOYOTA", "name_ar": "تويوتا" },
  { "id": 62, "name_en": "TESLA", "name_ar": "تيسلا" },
  { "id": 63, "name_en": "ABARTH", "name_ar": "ابارث" },
  { "id": 64, "name_en": "ACURA", "name_ar": "اكيورا" },
  { "id": 65, "name_en": "AMC", "name_ar": "اى ام سي" },
  { "id": 66, "name_en": "JEEP", "name_ar": "جيب" },
  { "id": 67, "name_en": "LINCOLN", "name_ar": "لينكون" },
  { "id": 68, "name_en": "MAZDA", "name_ar": "مازدا" },
  { "id": 69, "name_en": "MERCURY", "name_ar": "ميركوري" },
  { "id": 70, "name_en": "MINI COOPER", "name_ar": "ميني كوبر" },
  { "id": 71, "name_en": "VOLKSWAGEN", "name_ar": "فولكس واجن" },
  { "id": 72, "name_en": "VOLVO", "name_ar": "فولفو" },
  { "id": 73, "name_en": "ALFA ROMEO", "name_ar": "الفا رمويو" },
  { "id": 74, "name_en": "ASTON MARTIN", "name_ar": "استون مارتن" },
  { "id": 75, "name_en": "LAND ROVER", "name_ar": "لاند روفر" },
  { "id": 76, "name_en": "ROLLS ROYCE", "name_ar": "رولز رويس" },
  { "id": 77, "name_en": "MERCEDES", "name_ar": "مرسيدس" },
  { "id": 78, "name_en": "POLARIS", "name_ar": "بولاريس" },
  { "id": 79, "name_en": "INDIAN", "name_ar": "انديان" },
  { "id": 80, "name_en": "VICTORY", "name_ar": "فيكتوري" },
  { "id": 81, "name_en": "HARLEY DEVIDSON", "name_ar": "هارلي ديفيدسون" },
  { "id": 82, "name_en": "CHANGAN", "name_ar": "شانجان" },
  { "id": 83, "name_en": "GAC", "name_ar": "جاك قوناو" },
  { "id": 84, "name_en": "JAC", "name_ar": "جاك" },
  { "id": 85, "name_en": "PONTIAC", "name_ar": "بونتياك" },
  { "id": 86, "name_en": "CHERY", "name_ar": "شيري" },
  { "id": 87, "name_en": "HINO", "name_ar": "هينو" },
  { "id": 88, "name_en": "OLDSMOBILE", "name_ar": "اولدزموبيل" },
  { "id": 89, "name_en": "FOTON", "name_ar": "فوتون" },
  { "id": 90, "name_en": "BYD", "name_ar": "بي واي دي" },
  { "id": 91, "name_en": "GREAT WALL", "name_ar": "جريت وال" },
  { "id": 92, "name_en": "FAW", "name_ar": "فاو" },
  { "id": 93, "name_en": "MOTORCYCLE", "name_ar": "دراجة نارية" },
  { "id": 94, "name_en": "HAVAL", "name_ar": "هافال" },
  { "id": 95, "name_en": "BAIC", "name_ar": "بايك" },
  { "id": 96, "name_en": "SAIC", "name_ar": "سايك" },
  { "id": 97, "name_en": "KAWASAKI", "name_ar": "كاواساكي" },
  { "id": 98, "name_en": "MAN", "name_ar": "مان" },
  { "id": 99, "name_en": "RANGE ROVER", "name_ar": "رنج روفر" },
  { "id": 100, "name_en": "GENESIS", "name_ar": "جينيسيس" },
  { "id": 101, "name_en": "SHANGHAI", "name_ar": "شانقهاي" },
  { "id": 102, "name_en": "JMC", "name_ar": "JMC" },
  { "id": 103, "name_en": "CMC", "name_ar": "سي ام سي" },
  { "id": 104, "name_en": "ASHOK LEYLAND", "name_ar": "أشوك ليلاند" },
  { "id": 105, "name_en": "DONGFENG", "name_ar": "دونج فينج" },
  { "id": 106, "name_en": "MAXUS", "name_ar": "ماكسيوس" },
  { "id": 107, "name_en": "JETOUR", "name_ar": "جيتور" },
  { "id": 108, "name_en": "LUCID", "name_ar": "لوسيد" },
  { "id": 109, "name_en": "SINOTRUK", "name_ar": "سينوترك" },
  { "id": 110, "name_en": "HUANGHAI", "name_ar": "هوانجاي" },
  { "id": 111, "name_en": "CITREON", "name_ar": "سيتريون" },
  { "id": 112, "name_en": "LYNK & CO", "name_ar": "لينك اند كو" },
  { "id": 113, "name_en": "HONGQI", "name_ar": "هونشي" },
  { "id": 114, "name_en": "SHACMAN", "name_ar": "شاكمان" },
  { "id": 115, "name_en": "SCANIA", "name_ar": "سكانيا" },
  { "id": 116, "name_en": "GWM", "name_ar": "جي دبليو ام" },
  { "id": 117, "name_en": "SHAANXI", "name_ar": "شانكسي" },
  { "id": 119, "name_en": "ZX AUTO", "name_ar": "زي اكس اوتو" },
  { "id": 120, "name_en": "UD TRUCKS", "name_ar": "شاحنات يو دي" },
  { "id": 121, "name_en": "ANKAI", "name_ar": "انكاي" },
  { "id": 122, "name_en": "KING LONG", "name_ar": "كنق لونق" },
  { "id": 123, "name_en": "IVECO", "name_ar": "ايفيكو" },
  { "id": 124, "name_en": "GRAND TIGER", "name_ar": "قراند تايقر" },
  { "id": 125, "name_en": "SANY", "name_ar": "ساني" },
  { "id": 126, "name_en": "INTERNATIONAL", "name_ar": "انترناشيونال" },
  { "id": 127, "name_en": "CNHTC", "name_ar": "سي إن إتش تي سي" },
  { "id": 128, "name_en": "MATHIEU", "name_ar": "ماثيو" },
  { "id": 129, "name_en": "ZOTYE", "name_ar": "زوتي" },
  { "id": 130, "name_en": "JCB", "name_ar": "JCB" },
  { "id": 131, "name_en": "JAECOO", "name_ar": "JAECOO" },
  { "id": 132, "name_en": "HIGER", "name_ar": "HIGER" },
  { "id": 133, "name_en": "BOBCAT", "name_ar": "BOBCAT" },
  { "id": 134, "name_en": "BLK", "name_ar": "BLK" },
  { "id": 135, "name_en": "ZHONG TONG", "name_ar": "ZHONG TONG" },
  { "id": 996, "name_en": "تيدر", "name_ar": "تيدر" },
  { "id": 997, "name_en": "SHOVEL", "name_ar": "شيول" },
  { "id": 998, "name_en": "SEDAN", "name_ar": "سيدان" },
  { "id": 999, "name_en": "OTHER", "name_ar": "أخرى" }
]

vehicle_makes.each do |vehicle_make|
  VehicleMake.create!(
    id: vehicle_make[:id],
    name_en: vehicle_make[:name_en],
    name_ar: vehicle_make[:name_ar]
  )
end

ActiveRecord::Base.connection.reset_pk_sequence!("vehicle_makes")
