# === Faulty Configuration ===
#
# This file was generated by `rails generate faulty:install`
#
# 🚨 IMPORTANT: Update these settings to match your app
#   - config.current_faulty_user  → How Faulty finds your logged-in user
#   - config.authorized_users     → Who can access the Faulty dashboard
#
# Tip:
#   Use objects (e.g., User instances) instead of plain emails
#   for stronger integration with your app.
#
# Docs: https://your-gem-docs-url-here
#
# =============================

Faulty.configure do |config|
  # ✅ Environments where Faulty is enabled
  config.enabled_environments = %w[development staging production]

  # ✅ Defines how to resolve the current user
  # The `context` can be:
  #   - A Rails controller instance
  #   - A Rack env hash (if middleware)
  #
  # Must return the current logged-in user object.
  config.current_faulty_user = lambda do |context|
    # Example if you use CurrentAttributes:
    nil

    # Example with Devise:
    # context.respond_to?(:current_user) ? context.current_user : nil
  end

  # ✅ Toggle authorization checks for the Faulty dashboard
  config.enabled_authorization = false

  # ✅ Users allowed to access Faulty
  # Replace with User objects (recommended) inside the lambda, or keep empty to disable restrictions.
  #
  # Example (using ActiveRecord):
  # config.authorized_users = -> { User.where(role: :developer) }
  #
  # Example (manual list of objects):
  # config.authorized_users = -> { [User.find_by(email: "admin@example.com")] }
  #
  config.authorized_users = -> { [] }
end

# 🚨 Safety check: warn in production if no authorized users are set
if Rails.env.production? && (Faulty.authorized_users.blank?)
  Rails.logger.warn("[Faulty] No authorized users configured! Dashboard will be inaccessible.")
end
